### ISSUE TITLE
Closing task error

### ISSUE THREAD

**Issue by guillermodean** [guillermodean/PM_Suite#5]
Update the closing task function. it is requesting addition of times as if it is always called from the pomodoro script.

**Comment by guillermodean** [comment]
```
Enter the number of the task to close: 4
Traceback (most recent call last):
  File "c:\Users\DeanG\Desktop\python\PM_Suite-master\main.py", line 105, in <module>
    main()
  File "c:\Users\DeanG\Desktop\python\PM_Suite-master\main.py", line 84, in main
    tasks.listtask()
  File "c:\Users\DeanG\Desktop\python\PM_Suite-master\scripts\tasks.py", line 69, in listtask
    close_task(tasks)
  File "c:\Users\DeanG\Desktop\python\PM_Suite-master\scripts\tasks.py", line 44, in close_task
    closed_task['time_spent'] += closed_task['duration'] * 60  # Accumulate time spent in seconds
KeyError: 'duration'
```

**Comment by guillermodean** [comment]
fixed with previous commit
